baseURL = "http://sugarblank.dev/"
languageCode = "en-us"
title = "Bryan Rodriguez"
theme = "hello-friend-ng"


disableKinds	= ["RSS"]
[params]
  homeTitle = "Blank"
  enableSharingButtons = false
  homeSubtitle = "Software Developer"
  enableThemeToggle = true
  footerLeft = "Built differently &#8734;"
  footerRight = "By <a href=\"https://github.com/SugarBlank\">Scouri</a>"
  showReadingTime = false
    [languages.en.params.logo]
      logoMark     = "Î” ~ >>>"
      logoText = "SugarBlank"
      logoHomeLink = "/"
      logoCursorColor    = "#685c56"
      logoCursorAnimate = "2s"
    
    [params.portrait]
        path     = "/selfie.png"
        alt      = "Portrait"
        maxWidth = "150px"

  [[params.social]]
    name = "email"
    url  = "mailto:eneblank19@protonmail.com"

  [[params.social]]
    name = "github"
    url  = "https://github.com/SugarBlank"
  
  [[params.social]]
    name = "matrix"
    url  = "https://matrix.to/#/@scouri:matrix.org"

[menu]
  [[menu.main]]
    identifier = "about"
    name       = "About"
    url        = "about/"

  [[menu.main]]
    identifier = "projects"
    name       = "Projects"
    url        = "projects/"
  
  [[menu.main]]
    identifier	= "posts"
    name 	= "Posts"
    url		= "posts/"
